[package]
name = "lambc_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = "7.0.0"
thiserror = "1.0.56"

[dev-dependencies]
insta = "1.36.1"
pretty_assertions = "1.4.0"
