[package]
name = "lamb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
bindgen = "0.65.1"
cc = "1.0.73"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
