[package]
name = "lamb_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dumpster = { version = "0.1.2", features = ["derive"] }
lamb_ast = { path = "../lamb_ast" }
