[package]
name = "lamb_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lamb_ast = { path = "../lamb_ast" }
chumsky = { version = "1.0.0-6.alpha", features = ["pratt", "label"] }
